Traceback (most recent call last):
  File "/home/hargy/.local/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/hargy/.local/lib/python3.13/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/hargy/.local/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/hargy/.local/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/home/hargy/.local/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/hargy/.local/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from config.settings import ProjectRoot, LocalDataPath, PlotsPath
from config.plot_config import set_plot_style; set_plot_style()

# import the Waveform class
from models.waveform import Waveform

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import parameters
from config.run_params_1 import (
                            PEAK_THRESH,
                            INGRESS_THRESH,
                            ROI_t_runs,
                            ROI_t_calib
                            )
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mconfig[39;00m[38;5;21;01m.[39;00m[38;5;21;01msettings[39;00m [38;5;28;01mimport[39;00m ProjectRoot, LocalDataPath, PlotsPath
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mconfig[39;00m[38;5;21;01m.[39;00m[38;5;21;01mplot_config[39;00m [38;5;28;01mimport[39;00m set_plot_style; set_plot_style()
[1;32m      4[0m [38;5;66;03m# import the Waveform class[39;00m

[0;31mModuleNotFoundError[0m: No module named 'config.settings'

